- name: DSC example
  hosts: all

  tasks:

    - name: Get DSC module for Error Reporting configuration
      win_psmodule:
        name: cWindowsErrorReporting
        repository: PSGallery

    - name: Get DSC module for Certificates
      win_psmodule:
        name: CertificateDsc
        url: https://github.com/PowerShell/CertificateDsc
        
    - name: Export local certificate
      win_dsc:
        resource_name: CertificateDsc
        Type: 'CERT'
        Subject: 'WIN02'
        Path: 'c:\sslcert.cer'
